title = "Gitleaks Configuration"
# -------------------------------------------------------------------
# Production-grade config to detect secrets, API keys, and credentials
# -------------------------------------------------------------------

# =====================
# ALLOWLISTS (Global)
# =====================
[allowlist]
# Ignore non-sensitive directories or files
paths = [
  "test/"
]

# Common non-sensitive words to ignore
regexes = [
  "dummy",
  "example",
  "sample",
  "test_key",
  "notasecret",
  "public_key",
  "localhost"
]

# =====================
# RULES
# =====================

# --- Generic API Key ---
[[rules]]
id = "generic-api-key"
description = "Detect generic API keys or tokens"
regex = '''(?i)(?:api|key|token|secret|access|auth)[_-]?(?:key|token|id)?['"\s:=]{0,5}[A-Za-z0-9_\-]{20,}'''
entropy = 3.5
tags = ["apikey", "generic"]

# --- AWS Access Key ID ---
[[rules]]
id = "aws-access-key"
description = "AWS Access Key ID"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["aws", "apikey", "cloud"]

# --- AWS Secret Access Key ---
[[rules]]
id = "aws-secret-key"
description = "AWS Secret Access Key"
regex = '''(?i)aws(.{0,20})?(?:['"][0-9a-zA-Z\/+]{40}['"])'''
entropy = 4.0
tags = ["aws", "secret", "cloud"]

# --- GitHub Token ---
[[rules]]
id = "github-token"
description = "GitHub Personal Access Token"
regex = '''gh[pousr]_[A-Za-z0-9_]{36,}'''
tags = ["github", "token"]

# --- Google Cloud API Key ---
[[rules]]
id = "gcp-api-key"
description = "Google Cloud API Key"
regex = '''AIza[0-9A-Za-z\\-_]{35}'''
tags = ["gcp", "apikey"]

# --- Slack Token ---
[[rules]]
id = "slack-token"
description = "Slack token"
regex = '''xox[baprs]-[0-9A-Za-z-]{10,48}'''
tags = ["slack", "token"]

# --- Private Key Block ---
[[rules]]
id = "private-key"
description = "Private key block"
regex = '''-----BEGIN (EC|PGP|DSA|RSA|OPENSSH|PRIVATE) PRIVATE KEY-----'''
tags = ["key", "private"]

# --- Password in Code ---
[[rules]]
id = "password-assign"
description = "Hardcoded password"
regex = '''(?i)(password|passwd|pwd)\s*[:=]\s*['"][^'"]{6,}['"]'''
tags = ["password", "credential"]

# --- Database Connection String ---
[[rules]]
id = "db-connection-string"
description = "Database connection string"
regex = '''(?i)(postgres|mysql|mongodb|redis|sqlserver)(:\/\/)([^:@\s]+):([^:@\s]+)@([^:\s]+)'''
tags = ["db", "connection", "credential"]

# =====================
# END
# =====================
